# Simple workflow for deploying static content to GitHub Pages
name: Deploy font status to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout fontquery
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/fedora-i18n/fontquery
          cd fontquery
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install fontquery
        run: |
          pip install build wheel
          pushd fontquery
          python -m build
          pip install dist/fontquery*.whl
          popd
          rm -rf fontquery
      - name: Install dependencies
        run: sudo apt install podman buildah curl
      - name: Get supported releases
        id: vars
        run: (echo -n "fedora_releases=" && curl https://dl.fedoraproject.org/pub/fedora/imagelist-fedora | grep -E '(releases|development)/[0-9]+' | sed -e 's,.*/\([0-9]*\)/.*,\1,g' | sort | uniq | tr "\n" " ") >> $GITHUB_OUTPUT
      - name: Build pages
        run: |
          REL=""
          for i in ${{ steps.vars.fedora_releases }}; do
            REL="$REL -r $i"
          done
          if [ -z "$REL" ]; then
            echo "Unable to get supported releases"
            exit 1
          fi
          for t in minimal; do
            echo fontquery $REL -m html -t $t
            fontquery $REL -m html -t $t
          done
      - name: Build index
        run: |
          cp README.templ README.md
          for i in ${{ steps.vars.fedora_releases }}; do
            echo "* [$i](https://fedora-i18n.github.io/font-status/fedora-$i-minimal.html)" >> README.md
          done
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
