# Simple workflow for deploying static content to GitHub Pages
name: Deploy font status to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      force:
        description: "Force to build page"
        required: true
        type: boolean
        default: false
  schedule:
    - cron: '0 12 * * *'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  KEEP_WEEK: 12

jobs:
  check_releases:
    name: Check releases
    runs-on: ubuntu-latest
    outputs:
      fedora-matrix: ${{ steps.fedora.outputs.releases }}
      centos-matrix: ${{ steps.centos.outputs.releases }}
      date: ${{ steps.date.outputs.date }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout fontquery
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/fedora-i18n/fontquery
          cd fontquery
      - name: Get supported releases for Fedora
        id: fedora
        uses: ./fontquery/.github/actions/supported_releases
      - name: Get supported releases for CentOS
        id: centos
        uses: ./fontquery/.github/actions/centos_supported_releases
      - name: Clean up fontquery
        run: rm -rf fontquery
      - name: Set date
        id: date
        run: (echo -n "date=" && date +%Y%m%d) >> $GITHUB_OUTPUT

  iterate_gen_fedora_tables:
    needs:
      - check_releases
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        releases: ${{ fromJson(needs.check_releases.outputs.fedora-matrix) }}
        target: ["minimal"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup for fontquery
        uses: ./.github/actions/fqsetup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build JSON
        id: json
        uses: ./.github/actions/build
        with:
          product: "fedora"
          release: ${{ matrix.releases }}
          target: ${{ matrix.target }}

  iterate_gen_centos_tables:
    needs:
      - check_releases
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        releases: ${{ fromJson(needs.check_releases.outputs.centos-matrix) }}
        target: ["minimal"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup for fontquery
        uses: ./.github/actions/fqsetup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build JSON
        uses: ./.github/actions/build
        with:
          product: "centos"
          release: ${{ matrix.releases }}
          target: ${{ matrix.target }}

  commit_changes:
    needs:
      - iterate_gen_fedora_tables
      - iterate_gen_centos_tables
    runs-on: ubuntu-latest
    outputs:
      committed: ${{ steps.commit.outputs.committed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set date
        id: date
        run: (echo -n "date=" && date +%Y%m%d) >> $GITHUB_OUTPUT
      - name: Download results in matrix
        uses: dawidd6/action-download-artifact@v3
        with:
          name: "output-json-*"
          name_is_regexp: true
          run_id: ${{ github.run_id }}
          if_no_artifact_found: fail
      - name: Update JSON
        run: |
          for f in output-*/*.json; do
            mv $f json
          done
          rm -rf output-*
      - name: Add/Update JSON to git
        uses: EndBug/add-and-commit@v9
        id: commit
        with:
          add: json
          default_author: github_actions
          tag: '${{ steps.date.outputs.date }} --force'
          tag_push: '--force'

  iterate_gen_fedora_html:
    needs:
      - check_releases
      - iterate_gen_fedora_tables
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        releases: ${{ fromJson(needs.check_releases.outputs.fedora-matrix) }}
        target: ["minimal"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build HTML
        id: html
        uses: ./.github/actions/genhtml
        with:
          product: "fedora"
          release: ${{ matrix.releases }}
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
          max_count: ${{ env.KEEP_WEEK }}

  iterate_gen_centos_html:
    needs:
      - check_releases
      - iterate_gen_centos_tables
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        releases: ${{ fromJson(needs.check_releases.outputs.centos-matrix) }}
        target: ["minimal"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build HTML
        id: html
        uses: ./.github/actions/genhtml
        with:
          product: "centos"
          release: ${{ matrix.releases }}
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}

  # Single deploy job since we're just deploying
  deploy:
    needs:
      - check_releases
      - commit_changes
      - iterate_gen_fedora_html
      - iterate_gen_centos_html
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: ${{ needs.commit_changes.outputs.committed == 'true' || github.event.inputs.force == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download HTML files in matrix
        uses: dawidd6/action-download-artifact@v3
        with:
          name: "output-html-*"
          name_is_regexp: true
          run_id: ${{ github.run_id }}
          if_no_artifact_found: fail
      - name: Prepare HTML files
        run: |
          for f in output-html-*/*.html; do
            echo mv $f .
            mv $f .
          done
          rm -rf output-html-*
      - name: Normalize supported releases for Fedora
        id: fedora
        run: |
          echo ${{ needs.check_releases.outputs.fedora-matrix }} | sed -e 's/\[/releases=/' -e 's/\]//' -e 's/,/ /g' -e 's/"//g' >> $GITHUB_OUTPUT
      - name: Normalize supported releases for CentOS
        id: centos
        run: |
          echo ${{ needs.check_releases.outputs.centos-matrix }} | sed -e 's/\[/releases=/' -e 's/\]//' -e 's/,/ /g' -e 's/"//g' >> $GITHUB_OUTPUT
      - name: Build index
        run: |
          cp README.templ README.md
          mkdir used
          echo "### Fedora" >> README.md
          echo "" >> README.md
          for i in ${{ steps.fedora.outputs.releases }}; do
            echo -n "* $i \[" >> README.md
            for f in $(ls -1r fedora-$i*.html|head -${{ env.KEEP_WEEK }}); do
              d=$(echo $f|sed -e 's/.*-\([0-9]*\).html/\1/')
              mv $f used
              echo -n "[$d](https://fedora-i18n.github.io/font-status/$f) " >> README.md
            done
            echo "\]" >> README.md
          done
          echo "" >> README.md
          echo "### CentOS" >> README.md
          echo "" >> README.md
          for i in ${{ steps.centos.outputs.releases }}; do
            echo -n "* $i \[" >> README.md
            for f in $(ls -1r centos-$i*.html|head -${{ env.KEEP_WEEK }}); do
              d=$(echo $f|sed -e 's/.*-\([0-9]*\).html/\1/')
              mv $f used
              echo -n "[$d](https://fedora-i18n.github.io/font-status/$f) " >> README.md
            done
            echo "\]" >> README.md
          done
          rm *-[0-9]*.html || :
          mv used/* .
          rmdir used
          rm LICENSE || :
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          retention-days: 14
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
